// Generated by CoffeeScript 1.3.3
var ViewModel, tile, utils, vm,
  _this = this;

utils = this.utils;

ViewModel = (function() {

  function ViewModel(num) {
    this.contents = ko.observableArray([]);
  }

  return ViewModel;

})();

vm = new ViewModel(500);

tile = new Pinterest.Tile({
  container: "#container_dom",
  tile_width: 200,
  get_tiles: function() {
    return $('div[name="tile"]', $('#container_dom'));
  }
});

$(document).ready(function() {
  var url;
  ko.applyBindings(vm);
  url = 'http://ws.audioscrobbler.com/2.0/?method=tag.getweeklyartistchart&tag=female&api_key=b25b959554ed76058ac220b7b2e0a026&format=json';
  return utils.getJSON(url, function(data, dataType) {
    vm.contents(data.weeklyartistchart.artist);
    return tile.start();
  });
});
