// Generated by CoffeeScript 1.3.1
var ViewModel, tile, vm,
  _this = this;

ViewModel = (function() {

  function ViewModel(num) {
    var i;
    this.contents = (function() {
      var _i, _results;
      _results = [];
      for (i = _i = 1; 1 <= num ? _i <= num : _i >= num; i = 1 <= num ? ++_i : --_i) {
        _results.push(i);
      }
      return _results;
    })();
  }

  return ViewModel;

})();

vm = new ViewModel(50);

tile = new Pinterest.Tile({
  container_dom: "#container_dom",
  tile_width: 320,
  tile_top: 100,
  img_dom_height: 195,
  allcalc: true,
  inner_dom_func: function() {
    return $('div', $('#container_dom'));
  }
});

$(document).ready(function() {
  ko.applyBindings(vm);
  return tile.start();
});
