// Generated by CoffeeScript 1.3.3
var utils, _ref;

if ((_ref = this.utils) == null) {
  this.utils = {};
}

utils = this.utils;

utils.debug = true;

utils.log = function(obj) {
  if (utils.debug) {
    return console.log(obj);
  }
};

utils.getJSON = function(url, callback) {
  var opts;
  opts = {
    url: url,
    type: 'GET',
    traditional: true,
    cache: true,
    data: {},
    dataType: 'json',
    success: function(data, dataType) {
      utils.log(data);
      return callback(data);
    }
  };
  return $.ajax(opts);
};
